### PR TITLE
Notify clients of SignData changes. Fixes #88.

### LINKED ISSUE #88: Client not updated when sign changes.
I have been trying to create a PlayerInteractBlockEvent that changes a sign's text when it is right clicked. It has been impossible. I have been confirmed that there is an error in the implementation.
The following code was ran where *loc* was a valid sign placed in the world. The sign's text didn't change until the player disconnected and reconnected. Also [Here] (https://github.com/SpongePowered/SpongeAPI/issues/752) is a link to another issue where this was discussed.
```java
Optional<TileEntity> opTileEntity = loc.getTileEntity();
if (!opTileEntity.isPresent()) {
    System.out.println("Tile entity doesn't exist");
    return;
}
TileEntity signTile = opTileEntity.get();
Optional<SignData> optSignData = signTile.getOrCreate(SignData.class);
if (optSignData.isPresent()) {
    SignData sign = optSignData.get();
    sign.setLine(0, Texts.of("Some Text"));
    DataTransactionResult result = signTile.offer(sign);
    System.out.println(result);
} else {
    System.out.println("Data unable to be created");
}
```
(code by @simon816 )

### PR DESCRIPTION
**Pull request by JBYoshi**
This pull request fixes #88 by marking signs as dirty when new `SignData` is offered to them.

### CODE REVIEW

**Comment by modwizcode** [comment]
I tried applying a similar fix when working on the Stargate's plugin and markDirty wasn't solving the issue for me. I ended up having to call a method on `net.minecraft.world.World` that marked the block as needing to be updated.

**Comment by ryantheleach** [comment]
World.markBlockForUpdate(BlockPos)

**Comment by JBYoshi** [comment]
I'll close this and make a new one for the Value API if necessary.

**Comment by gabizou** [comment]
@JBYoshi I've noticed the change required, as all `DataProcessor`s have to be changed for the update, I'll make the mental note to ensure they keep this type of change as I progress with the implementation in #94. If possible, I'd appreciate any double checks and or contributions if you can follow the implementation and understand it, I'm available on IRC most of the time.

**Pull request closed without merging**
