### PR TITLE
Fixing some problems with blockData

### PR DESCRIPTION
**Pull request by lucdon**
@gabizou, @bloodmc thoughts?

### CODE REVIEW

**Comment by gabizou** [comment]
@lucdon While it's normally inexpensive, I'd rather it's left to the block to determine whether extended properties are needed. Calling extended properties for every block is somewhat costly imo.

**Comment by lucdon** [comment]
@gabizou so you want to leave it as it is now? i created this pr because @bloodmc had some issues with how it is atm.

**Comment by gabizou** [comment]
@lucdon can you re-test after rebasing on master?

**Comment by Aaron1011** [comment]
@lucdon: Can you rebase this against master?

**Comment by lucdon** [comment]
@gabizou  @Aaron1011  bit late but done!

**Comment by gabizou** [comment]
Awesome, thanks @lucdon .

**Pull request merged**
