### PR TITLE
Fixes Hotbar#setSelectedSlotIndex

### LINKED ISSUE #487: ClassCastException when using Hotbar#setSelectedSlotIndex
```java
((Hotbar)player.getInventory().query(Hotbar.class)).setSelectedSlotIndex(0);
```

https://github.com/SpongePowered/SpongeCommon/blob/a493433e40298c8a82a75b446646dc46176f14ea/src/main/java/org/spongepowered/common/item/inventory/lens/impl/comp/HotbarLensImpl.java#L75

### PR DESCRIPTION
**Pull request by Faithcaio**
Fixes #487 ClassCastException when using Hotbar#setSelectedSlotIndex

### CODE REVIEW

**Comment by windy1** [comment]
This should be targeting the bleeding branch, no?

**Comment by kashike** [comment]
this isn't a breaking change

**Comment by liach** [comment]
@windy1 I suggest you to pull on your client with fast foward and push to the github repo to prevent extra merge commits.

**Comment by kashike** [comment]
@liach we merge now. https://docs.spongepowered.org/en/contributing/versioning.html

**Comment by Mumfrey** [comment]
@windy1 did you merge this with the github merge button?

**Comment by windy1** [comment]
Yes @Mumfrey, is there a problem with that?

**Comment by liach** [comment]
@kashike I mean not to use github non ft merge.

**Comment by Mumfrey** [comment]
@windy1 no massive problem no but when we decided to adopt merges it was generally accepted that we would try to make merge messages as descriptive as possible so that they contextualise the merge. So for example if you're merging a feature branch you could use:

    Merged feature *blah*

or for a pull request like this it could be

    Merged fix for `Hotbar#setSelectedSlotIndex

Since it's just easier to see what's what when you're reading the commit log that way. If it just says the unhelpful github default `merged x from y` it's just a bit naff basically.

No problem this time, just telling you for future reference.

**Comment by windy1** [comment]
Okay great, thanks for the info @Mumfrey

**Pull request merged**
