### PR TITLE
Perform IP Forwarding tasks earlier in the handshake process.

### PR DESCRIPTION
**Pull request by dualspiral**
In order to be able to use the latest iteration of IP Forwarding for Bungee and Forge clients and thus achieve zero configuration on the Bungee side without breaking backwards compatibility, we need to be able to read the LoginProfile properties much earlier than we do right now, so we can indicate to SpongeForge that the user is a Forge client with zero config.

This does not impact on the existing implementation, it simply moves the checks.

Context for this change: https://github.com/SpigotMC/BungeeCord/pull/1557#issuecomment-158671754
Related SpongeForge PR: https://github.com/SpongePowered/SpongeForge/pull/424

### CODE REVIEW

**Comment by Minecrell** [comment]
Could you make sure that this is also working on SpongeVanilla? Are there additional changes necessary there?

**Comment by dualspiral** [comment]
I'll check, but it should just work with no additional changes.

**Comment by Minecrell** [comment]
@dualspiral You'll probably need to add the [BungeeCord mixin config](https://github.com/SpongePowered/SpongeVanilla/blob/master/src/main/java/org/spongepowered/server/launch/VanillaServerTweaker.java#L125-L128) for SpongeCommon first.

**Comment by dualspiral** [comment]
Heh, forgot about that. Will test and PR any changes needed then, you'd need it for the current implementation anyway.

**Comment by dualspiral** [comment]
@Minecrell It works fine with SpongeVanilla once you add the BungeeCord plugin, as you suggested - https://github.com/dualspiral/SpongeVanilla/commit/dae786e5ae58bc79f47aecefc8d7eb8583fa6504 is all it needs to work.

My test plugin to verify this can be found at https://gist.github.com/dualspiral/abc96bd5e06c717e4818, noting that Sponge could get my UUID successfully.

I won't bother making a PR for this into Vanilla as it is a one line change, unless you really want me to!

**Comment by Minecrell** [comment]
@dualspiral Awesome, thanks a lot for testing. No need to make a PR, I'll pull your commit in as soon this is merged.

**Comment by dualspiral** [comment]
@bloodmc This will need merging in order for the PR that was merged in https://github.com/SpongePowered/SpongeForge/pull/424 to be effective (sorry, should have made that clear in the other PR!).

**Pull request closed without merging**
