### PR TITLE
Implement PotionData for tipped arrows

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by JBYoshi** [comment]
Is there already support for `PotionData` on tipped arrow `ItemStack`s? If not, could you add that as well?

**Comment by jamierocks** [comment]
@JBYoshi I'll get on that when I'm back ;)

**Comment by jamierocks** [comment]
That should do the trick ;)

**Comment by JBYoshi** [comment]
I actually meant the tipped arrow item. It appears to use the [same NBT structure](http://minecraft.gamepedia.com/Player.dat_format#Potion_Effects) as potions though, so it shouldn't be too much work to add it in.

**Comment by jamierocks** [comment]
See https://github.com/jamierocks/SpongeCommon/blob/3fe1774416c8af6f22a61942f597c3a3bb0a94a3/src/main/java/org/spongepowered/common/data/processor/data/item/ItemPotionDataProcessor.java#L54

**Comment by JBYoshi** [comment]
`Items.TIPPED_ARROW`? I don't see that. I just see `Items.POTIONITEM`, `Items.SPLASH_POTION`, and `Items.LINGERING_POTION`.

**Comment by jamierocks** [comment]
Ah yes - all I could remember of your original comment was item and potion. I'll get on it.

**Pull request merged**
