### PR TITLE
Implementation of SneakingData

### PR DESCRIPTION
**Pull request by joshgarde**
SneakingData implemented

### CODE REVIEW

**Comment by ryantheleach** [comment]
As a tip if you push to the same branch as an already open PR it will update the PR without you having to create another, it also preserves the history of what you have tried so whilst reviewing people can see how the PR has changed.

**Comment by joshgarde** [comment]
Ah so this is why ``DataManipulator``s like ``SneakingData`` haven't been implemented yet.
https://github.com/SpongePowered/SpongeCommon/pull/94 - DataAPI 2.0

**Comment by me4502** [comment]
Please update this to the current data API.

**Comment by gabizou** [comment]
You need to `git rebase sponge/master`.

**Comment by joshgarde** [comment]
SneakingData implementation - done & updated.

**Comment by simon816** [comment]
You've rebased wrong and have a bunch of commits that shouldn't be there. This is (one of) the reasons why PRing on your `master` branch is a bad idea.
Needs to be fixed

**Comment by joshgarde** [comment]
Updated pull request with new DataAPI and fixed commits - https://github.com/SpongePowered/SpongeCommon/pull/135

**Pull request closed without merging**
