### PR TITLE
Begin work on recipes

### PR DESCRIPTION
**Pull request by kashike**
[API](https://github.com/SpongePowered/SpongeAPI/pull/1098) | [**Common**](https://github.com/SpongePowered/SpongeCommon/pull/532)

### CODE REVIEW

**Comment by kashike** [comment]
Implementation might not be done for a while yet: https://github.com/SpongePowered/SpongeAPI/pull/1098#issuecomment-188300093

**Comment by Limeth** [comment]
Anything I could help with?

**Comment by liach** [comment]
@kashike You should close this one since the one for API is superseded.

**Comment by kashike** [comment]
Thought this was already closed - thanks @liach.

**Pull request closed without merging**
