### PR TITLE
Fixed onShiftClick attribute generation code.

### LINKED ISSUE #437: TextXML can't survive a roundtrip.
```
xml = TextSerializers.TEXT_XML.serialize(message);
p.sendMessage(ChatTypes.CHAT, TextSerializers.TEXT_XML.deserialize(xml)));
```
results in an exception being thrown. the xml deserializer can't handle the encoded <> symbols that it outputs as a valid onclick listener.

```
[08:31:22] [pool-2-thread-1/ERROR] [TranslateWithBing]: threw an exception while parsing xml
org.spongepowered.api.text.serializer.TextParseException: Error parsing TextXML message
	at org.spongepowered.common.text.serializer.xml.TextXmlTextSerializer.deserialize(TextXmlTextSerializer.java:95) ~[TextXmlTextSerializer.class:?]
	at au.id.rleach.translate.TranslateWithBing.lambda$null$3(TranslateWithBing.java:98) ~[TranslateWithBing.class:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_66]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_66]
	at au.id.rleach.translate.TranslateWithBing.lambda$null$4(TranslateWithBing.java:98) ~[TranslateWithBing.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_66]
	at au.id.rleach.translate.TranslateWithBing.lambda$sendTranslatedMessages$5(TranslateWithBing.java:88) ~[TranslateWithBing.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$9(Task.java:138) ~[Task$Builder.class:?]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$2(SchedulerBase.java:177) ~[SchedulerBase.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.RuntimeException: Invalid click handler
	at org.spongepowered.common.text.serializer.xml.Element.applyTextActions(Element.java:108) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.toText(Element.java:163) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.builderFromObject(Element.java:172) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Tr.toText(Tr.java:55) ~[Tr.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.builderFromObject(Element.java:172) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.toText(Element.java:149) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.builderFromObject(Element.java:172) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.toText(Element.java:149) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.TextXmlTextSerializer.deserialize(TextXmlTextSerializer.java:93) ~[TextXmlTextSerializer.class:?]
	... 14 more
[08:31:22] [pool-2-thread-1/ERROR] [TranslateWithBing]: 

```

```
<span><tr key="chat.type.text"><span onClick="suggest_command('/msg Player385 ')" onShiftClick="insert_text('Player385)" onHover="show_entity('&lt;span&gt;{name:&quot;Player385&quot;,id:&quot;1e3c9076-6029-36c6-8475-dd38d2030d5f&quot;}&lt;/span&gt;')"><span>Player385</span></span><span>test</span></tr></span>
```

### PR DESCRIPTION
**Pull request by TomyLobo**
Fixes #437

### CODE REVIEW

**Comment by ryantheleach** [comment]
Does this relate to #492

**Comment by TomyLobo** [comment]
This isn't merged yet?

**Comment by gabizou** [comment]
@Minecrell @windy1 any objections to merging this?

**Comment by kashike** [comment]
This should be merged, I'm surprised it hasn't been already

**Comment by windy1** [comment]
No objection here.

**Comment by TomyLobo** [comment]
That looks like an unrelated commit you glued it onto.
Bad practice, but oh well, at least it's finally in...

**Comment by Zidane** [comment]
@TomyLobo 

Its a small change, not dedicating a commit for that.

**Comment by TomyLobo** [comment]
Like I said, bad practice.
See also:
https://crealytics.com/blog/2010/07/09/5-reasons-keeping-git-commits-small/

This post also brings up the important point of backporting fixes:
http://stackoverflow.com/a/6544568

**Pull request closed without merging**
