### PR TITLE
Fix world loading when allow-nether is false

### PR DESCRIPTION
**Pull request by JBYoshi**
This pull request prevents worlds, other than the overworld, from loading if `allow-nether` in server.properties is set to false. See #118.

### CODE REVIEW

**Comment by me4502** [comment]
I'm not sure if I agree with this.

That option disables the vanilla nether, which is still possible with multi world support.

**Comment by JBYoshi** [comment]
@me4502 According to blood in SpongePowered/SpongeCommon#287:

> We will be handling "allow-nether" as allowMultipleDimensions to be consistent with Forge. 

And:
> I pushed a new branch 'world-update' which has the functionality you need via our world configs. To disable a world or dimension, locate the config under ./config/Sponge and set 'world-enabled' to false.

**Comment by Zidane** [comment]
@JBYoshi 

Not sure if I want to even honor that setting via Vanilla. @bloodmc do we want to keep this to our configs or allow this as a "vanilla-override"

**Comment by JBYoshi** [comment]
@Zidane @bloodmc Status?

**Comment by bloodmc** [comment]
@JBYoshi Please update this branch with current master.

**Comment by JBYoshi** [comment]
@bloodmc Done.

**Pull request closed without merging**
