### PR TITLE
Fix : The offline players have no skin

### PR DESCRIPTION
**Pull request by rexbut**
Test code : https://github.com/rexbut/EverEssentials/blob/master/EESkull.java

### CODE REVIEW

**Comment by gabizou** [comment]
What are the implications of this running on an offline server and such?

**Comment by rexbut** [comment]
When adding a GameProfile to disconnected player on a ItemType.Skull head has no texture

**Comment by rexbut** [comment]
Yes it works on offline server because I reused the method "setProfile" a TileEntitySkull

**Comment by rexbut** [comment]
Bug :
setProfile(TileEntitySkull skull, @Nullable GameProfile profile) : download texture
setProfile(ItemStack skull, @Nullable GameProfile profile) : no download texture

**Comment by rexbut** [comment]
On an offline server there may be a warning like a vanilla minecraft server (1.8.9 and 16w07b) when you place an unofficial player head on the ground .

> [16:57:58] [Server thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@481ed0a5[id=173694ba-40d3-367e-a62e-e144e879ff2b,name=te,properties={},legacy=false]
> com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
> 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[minecraft_server.16w07b.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [minecraft_server.16w07b.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [minecraft_server.16w07b.jar:?]
> 	at aqn.b(SourceFile:144) [minecraft_server.16w07b.jar:?]
> 	at aqn.g(SourceFile:120) [minecraft_server.16w07b.jar:?]
> 	at aqn.a(SourceFile:116) [minecraft_server.16w07b.jar:?]
> 	at aep.a(SourceFile:82) [minecraft_server.16w07b.jar:?]
> 	at adp.a(SourceFile:134) [minecraft_server.16w07b.jar:?]
> 	at ls.a(SourceFile:337) [minecraft_server.16w07b.jar:?]
> 	at mb.a(SourceFile:633) [minecraft_server.16w07b.jar:?]
> 	at jg.a(SourceFile:55) [minecraft_server.16w07b.jar:?]
> 	at jg.a(SourceFile:11) [minecraft_server.16w07b.jar:?]
> 	at fh$1.run(SourceFile:13) [minecraft_server.16w07b.jar:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
> 	at g.a(SourceFile:45) [minecraft_server.16w07b.jar:?]
> 	at net.minecraft.server.MinecraftServer.D(SourceFile:597) [minecraft_server.16w07b.jar:?]
> 	at la.D(SourceFile:339) [minecraft_server.16w07b.jar:?]
> 	at net.minecraft.server.MinecraftServer.C(SourceFile:553) [minecraft_server.16w07b.jar:?]
> 	at net.minecraft.server.MinecraftServer.run(SourceFile:457) [minecraft_server.16w07b.jar:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Comment by Aaron1011** [comment]
It's now possible to `fill` a `GameProfile` yourself using the `GameProfileManager`, which works in both offline and online mode.

@kashike and I will be addressing some usability problems with `GameProfileManager` and `GameProfileCache` in the near future.

**Pull request closed without merging**
