### PR TITLE
README.md Update

### PR DESCRIPTION
**Pull request by Grinch**
Addresses issue #3.

Signed-off-by: Steven Downer <grinch@outlook.com>

### CODE REVIEW

**Comment by gabizou** [comment]
Possibly elaborate how this is a common repository for the current (two) implementations of SpongeAPI?

**Comment by Deamon5550** [comment]
I would think that we would be probabl wanting to remove the information on running from this repo's readme, as running requires one of the implementations not just this repo.

**Comment by Grinch** [comment]
@Deamon5550 Where in this README does it state how to run it?

@gabizou Never really been good with explaining things so if you have a better description to put there, let me know and I'll make the change.

**Comment by Deamon5550** [comment]
@Grinch Sorry my mistake

**Comment by gabizou** [comment]
@Grinch I think @Zidane had a very good description of it.

**Pull request closed without merging**
