### PR TITLE
Implement FireworkData

### PR DESCRIPTION
**Pull request by ZephireNZ**
API side: SpongePowered/SpongeAPI#902

Implementation of `REPLACE_WITH_DATA_MANIPULATOR`.
- [ ] Registration of field getters and setters
- [ ] Accurately used the appropriate `AbstractData` implementation

Implementation of `REPLACE_WITH_IMMUTABLE_MANIPULATOR`
- [ ] Accurately extended the appropriate `AbstractImmutableData` implementation
- [ ] Accurately instantiating final instance fields with an `ImmutableValue` counter part for any value getters
- [ ] If necessary, creating a new `ImmutableValue` for a value that should not be cached, or, using the existing caching utils.

Implementation of the `VALUE_PROCESSOR`(s):
- [ ] Appropriately extended `AbstractSpongeValueProcessor`
- [ ] Individual processors for each source type possible (one for `ItemStack`/`TileEntity`/`Entity` as necessary).

Registration:
- [ ] Registered the `Key` correctly by `FIELD_NAME` in the `KeyRegistry`
- [ ] Registered the `DataProcessor`s and `DataManipulatorBuilder` in `SpongeSerializationRegistry`
- [ ] Registered the `ValueProcessor`s in the `SpongeSerializationRegistry`

```java
@Plugin(id = "data-test", name = "DataTest")
public class DataTest {

    @Listener
    public void onClick(InteractEvent event) {
        FireworkEffect effect =  event.getGame().getRegistry()
                .createFireworkEffectBuilder()
                .color(Color.BLUE)
                .shape(FireworkShapes.BALL)
                .flicker(true)
                .build();

        if(event.getCause().any(Player.class)) {
            Player player = event.getCause().first(Player.class).get();
            if(player.getItemInHand().isPresent()) {
                ItemStack item = player.getItemInHand().get();
                if(item.get(FireworkEffectData.class).isPresent()) {
                    FireworkEffectData data = item.get(FireworkEffectData.class).get();
                    if(data.get(Keys.FIREWORK_EFFECTS).isPresent()) {
                        List<FireworkEffect> effects = data.get(Keys.FIREWORK_EFFECTS).get();
                        System.out.println("Effects: " + effects.toString());
                        data.set(Keys.FIREWORK_EFFECTS, ImmutableList.of(effect));
                        item.offer(data);
                        System.out.println("New Effects: " + item.get(Keys.FIREWORK_EFFECTS).get());
//                        System.out.println("Remove Effects Result: " + item.remove(Keys.FIREWORK_EFFECTS).getType().name());
                        System.out.println("Effects Present : " + item.get(Keys.FIREWORK_EFFECTS).isPresent());
                        player.setItemInHand(item);
                    }
                } else {
                    System.out.println("Effects not present");
                }

                if(item.get(FireworkRocketData.class).isPresent()) {
                    FireworkRocketData data = item.get(FireworkRocketData.class).get();
                    if(data.get(Keys.FIREWORK_FLIGHT_MODIFIER).isPresent()) {
                        Integer modifier = data.get(Keys.FIREWORK_FLIGHT_MODIFIER).get();
                        System.out.println("Modifier: " + modifier);
                        data.set(Keys.FIREWORK_FLIGHT_MODIFIER, 10);
                        item.offer(data);
                        System.out.println("New Modifier: " + item.get(Keys.FIREWORK_FLIGHT_MODIFIER).get());
//                        System.out.println("Remove Modifier Result: " + item.remove(Keys.FIREWORK_FLIGHT_MODIFIER).getType().name());
                        System.out.println("Modifier Present: " + item.get(Keys.FIREWORK_FLIGHT_MODIFIER).isPresent());
                        player.setItemInHand(item);
                    }
                } else {
                    System.out.println("Modifier not present");
                }

            }
        }
    }

}
```

### CODE REVIEW

**Comment by ZephireNZ** [comment]
Test plugin: Coming to theatres Summer 2015!

**Comment by gabizou** [comment]
> Coming to theatres Summer 2015!

A little late there, eh?

**Comment by ZephireNZ** [comment]
Forgive me, everything is backwards down here ;)

**Comment by ZephireNZ** [comment]
@gabizou Test done - have fun!

**Pull request closed without merging**
